# Required environment variables:
# RELEASES_REPO
# SNAPSHOTS_REPO
# REPO_
language: java

jdk:
  - oraclejdk8
  - oraclejdk7

before_script:
  - echo "REPO_USER_ID  = ${REPO_USER_ID}"
  - echo "RELEASES_REPO = ${RELEASES_REPO}"

after_success:
  - mvn deploy --settings settings.xml
